---
# tasks file for secirity-group
-   name: Create security group
    ec2_group:
        name: "jmsth_security_group"
        description: "jmsth security group"
        region: ap-south-1	
        rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
        rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
    register: basic_firewall
